### ISSUE TITLE
Players and non-players are able to delete rows in the game board

### ISSUE THREAD

**Issue by johnbeech** [dustincchan/Codenames_On_Slack#1]
Users are able to delete rows of the board, which kind of breaks the game:
<img width="605" alt="delete-rows" src="https://user-images.githubusercontent.com/6341696/27175640-b23a3f1e-51b7-11e7-820e-6edc6891b120.png">

**Comment by dustincchan** [comment]
Thanks for your feedback, but I am unable use the app to prevent anyone with admin rights from deleting messages in a channel.
