### ISSUE TITLE
Sensitive information on settings.py

### ISSUE THREAD

**Issue by mawkee** [dustincchan/Codenames_On_Slack#2]
https://github.com/dustincchan/Codenames_On_Slack/blob/53eb3229b6aab4afac8f342c22bb04f2edd35065/codenames/settings.py#L45
https://github.com/dustincchan/Codenames_On_Slack/blob/53eb3229b6aab4afac8f342c22bb04f2edd35065/codenames/settings.py#L25

I don't think these should be here

**Comment by dustincchan** [comment]
@mawkee, fixed in b696879. thank you for pointing it out
