### ISSUE TITLE
Install Codenames on Slack leads to Error

### ISSUE THREAD

**Issue by ttran428** [dustincchan/Codenames_On_Slack#6]
When I try to click on the "install on slack" button on `http://codenames-slack.herokuapp.com/`,  I get the error `OAuth Error: Invalid client_id parameter`. I am not sure why this is happening, and I've tried it on Chrome and Safari as well as in incognito mode.

**Comment by maxov** [comment]
Also running into this issue 😢 Would appreciate a fix!

**Comment by dustincchan** [comment]
Oh noes, maybe something expired. I'll see if I can reproduce this to fix it. Thanks.

**Comment by dustincchan** [comment]
Please try again. It should work. (see: 54a95da3ac6cdb64f1fac3312733cd0be2b5720f)

**Comment by ttran428** [comment]
Thanks so much! It works now <3
